[package]
name = "health-coach"
version = "0.1.0"
edition = "2021"

[dependencies]
chotu-common = { path = "../chotu-common" }
tokio = { workspace = true }
sqlx = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
teloxide = { workspace = true }
uuid = { workspace = true }
schemars = { workspace = true }
